### PR TITLE
Update Get Bangumi Detail->Parameters:id description

### PR DESCRIPTION
**Pull request by kslr**
Get Bangumi Detail->Parameters : id | description : bangumi id
but should be id ( such as 46a469ee-5041-4f7c-8bf3-43ea6166a728 )

### CODE REVIEW

**Comment by lordfriend** [comment]
It is actually bangumi id, In our project we try bangumi.tv information as special meaning, for example we describe bgm_id as *id of bangumi in bangumi.tv* . So in this position, bangumi id is the right description.

**Comment by kslr** [comment]
But using bgm_id will get sql error,  uuid is working properly.

cursor.execute(statement, parameters)\nDataError: (psycopg2.DataError) invalid input syntax for uuid: "189784"\nLINE 3: ...HERE bangumi.delete_mark IS NULL AND bangumi.id = \'189784\' O...\n                                                             ^\n [SQL: \'SELECT bangumi.id AS bangumi_id, bangumi.bgm_id AS bangumi_bgm_id, bangumi.name AS bangumi_name, bangumi.name_cn AS bangumi_name_cn, bangumi.type AS bangumi_type, bangumi.eps AS bangumi_eps, bangumi.summary AS bangumi_summary, bangumi.image AS bangumi_image, bangumi.air_date AS bangumi_air_date, bangumi.air_weekday AS bangumi_air_weekday, bangumi.rss AS bangumi_rss, bangumi.dmhy AS bangumi_dmhy, bangumi.eps_no_offset AS bangumi_eps_no_offset, bangumi.acg_rip AS bangumi_acg_rip, bangumi.libyk_so AS bangumi_libyk_so, bangumi.bangumi_moe AS bangumi_bangumi_moe, bangumi.eps_regex AS bangumi_eps_regex, bangumi.status AS bangumi_status, bangumi.create_time AS bangumi_create_time, bangumi.update_time AS bangumi_update_time, bangumi.delete_mark AS bangumi_delete_mark, episodes_1.id AS episodes_1_id, episodes_1.bangumi_id AS episodes_1_bangumi_id, episodes_1.bgm_eps_id AS episodes_1_bgm_eps_id, episodes_1.episode_no AS episodes_1_episode_no, episodes_1.name AS episodes_1_name, episodes_1.name_cn AS episodes_1_name_cn, episodes_1.duration AS episodes_1_duration, episodes_1.airdate AS episodes_1_airdate, episodes_1.status AS episodes_1_status, episodes_1.create_time AS episodes_1_create_time, episodes_1.update_time AS episodes_1_update_time, episodes_1.delete_mark AS episodes_1_delete_mark \\nFROM bangumi LEFT OUTER JOIN episodes AS episodes_1 ON bangumi.id = episodes_1.bangumi_id \\nWHERE bangumi.delete_mark IS NULL AND bangumi.id = %(id_1)s ORDER BY episodes_1.episode_no\'] [parameters: {\'id_1\': u\'189784\'}]\n' (unicode)

**Comment by lordfriend** [comment]
bgm_id is **id of the bangumi in bangumi.tv** which will use a disambiguated description. bangumi means bangumi literally, not the bangumi.tv. so the id of bangumi.
PS: bgm_id is integer and bangumi id is an uuid (in HTTP API is string). It is not easy to confusion

**Comment by kslr** [comment]
Ok.

**Pull request closed without merging**
