### PR TITLE
Color placeholder

### PR DESCRIPTION
**Pull request by lordfriend**

### CODE REVIEW

**Comment by kslr** [comment]
Is it used as a pre-placeholder for loading a picture?

**Comment by lordfriend** [comment]
Yes, the idea is brought from this article http://blog.learningspaces.io/color-placeholders-for-loading-images/

**Comment by lordfriend** [comment]
Warning: This alembic upgrade scripts will check exist images that will make the progress will slow.

**Comment by kslr** [comment]
Ok 👍

**Pull request merged**
