### PR TITLE
Fix episode matching

### PR DESCRIPTION
**Pull request by qip**
Add `\s(\d+)$` to current regex list.
For instance, searching "半泽直树" in dmhy returns "日菁字幕組 半澤直樹 01" while no episode number is matched to it with current master or dev branch.

### CODE REVIEW

**Comment by lordfriend** [comment]
Thank you for contributing!
For the stability reason, Would please make a new PR to `dev` branch first?  I will test it on test environment and then merge this PR.

**Comment by qip** [comment]
Ah sure. I'm going to close this one then.

**Comment by qip** [comment]
Sure, will do.

**Comment by qip** [comment]
I've re-opened this one for merging after testing.

**Pull request merged**
